-- MySQL Script generated by MySQL Workbench
-- Sun Mar 16 08:49:08 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cana_acucar
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cana_acucar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cana_acucar` DEFAULT CHARACTER SET utf8mb4 ;
USE `cana_acucar` ;

-- -----------------------------------------------------
-- Table `cana_acucar`.`impactos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cana_acucar`.`impactos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(50) NULL DEFAULT NULL,
  `descricao` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cana_acucar`.`cana`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cana_acucar`.`cana` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `familia` VARCHAR(100) NULL DEFAULT NULL,
  `tipo` VARCHAR(50) NULL DEFAULT NULL,
  `origem` VARCHAR(100) NULL DEFAULT NULL,
  `impactos_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cana_impactos1_idx` (`impactos_id` ASC) VISIBLE,
  CONSTRAINT `fk_cana_impactos1`
    FOREIGN KEY (`impactos_id`)
    REFERENCES `cana_acucar`.`impactos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cana_acucar`.`usos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cana_acucar`.`usos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` TEXT NOT NULL,
  `impactos_id` INT(11) NOT NULL,
  `usoscol` VARCHAR(45) NULL,
  `usoscol1` VARCHAR(45) NULL,
  `usoscol2` VARCHAR(45) NULL,
  `usoscol3` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usos_impactos1_idx` (`impactos_id` ASC) VISIBLE,
  CONSTRAINT `fk_usos_impactos1`
    FOREIGN KEY (`impactos_id`)
    REFERENCES `cana_acucar`.`impactos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cana_acucar`.`producao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cana_acucar`.`producao` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `ano` INT(11) NOT NULL,
  `quantidade` DECIMAL(10,2) NULL DEFAULT NULL,
  `unidade` VARCHAR(20) NULL DEFAULT NULL,
  `id_cana` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_cana` (`id_cana` ASC) VISIBLE,
  INDEX `fk_producao_usos1_idx` (`ano` ASC, `id` ASC, `quantidade` ASC, `unidade` ASC, `id_cana` ASC) VISIBLE,
  CONSTRAINT `producao_ibfk_1`
    FOREIGN KEY (`id_cana`)
    REFERENCES `cana_acucar`.`cana` (`id`),
  CONSTRAINT `fk_producao_usos1`
    FOREIGN KEY (`ano` , `id` , `quantidade` , `unidade` , `id_cana`)
    REFERENCES `cana_acucar`.`usos` (`descricao` , `id` , `id` , `id` , `id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
